name: Lint

on:
  pull_request:
    branches: ["*"]
    types:
      - opened
      - synchronize
      - closed
  push:
    branches: [main, dev]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  backend-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"
      - run: pip install poetry
      - run: poetry install
      - run: poetry run ruff format neosr --check

  backend-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"
      - run: pip install poetry
      - run: poetry install
      - run: poetry run ruff check neosr
